name: Validate PR
on:
  pull_request:
    branches: [ master ]
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v2
      - run: |
            # install deps
            dotnet tool restore
            # run format checker
            dotnet csharpier --check
